/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.models.SerieManager;
import com.mycompany.views.components.SerieItem;

import java.util.ArrayList;

/**
 *
 * @author famar
 */
public class App extends javax.swing.JFrame {

    final SerieManager managerSerie;

    /**
     * Creates new form App
     */
    public App() {
        //TODO: la SearchBox hacerla un componente
        managerSerie = new SerieManager("series.db");
        ArrayList<SerieItem> serieListComponents = new ArrayList<SerieItem>();

        initComponents();

        for (var serie : managerSerie.getSeries()) {
            SerieItem serieItem = new SerieItem(serie);

            jPanel1.add(serieItem);
            serieListComponents.add(serieItem);
        }

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Header = new javax.swing.JPanel();
        ButtonOptions = new javax.swing.JButton();
        ButtonRefreshAvailabilitySerie = new javax.swing.JButton();
        SearchBox = new javax.swing.JTextField();
        ButtonAddSerie = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MySeries App");
        setMinimumSize(new java.awt.Dimension(550, 700));

        jSplitPane1.setDividerLocation(60);
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        ButtonOptions.setText("⚙");

        ButtonRefreshAvailabilitySerie.setText("🔄");
        ButtonRefreshAvailabilitySerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRefreshAvailabilitySerieActionPerformed(evt);
            }
        });

        SearchBox.setToolTipText("Search your serie...");
        SearchBox.setName("search"); // NOI18N

        ButtonAddSerie.setText("➕");
        ButtonAddSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ButtonRefreshAvailabilitySerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonAddSerie)
                .addGap(61, 61, 61)
                .addComponent(SearchBox, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(ButtonOptions)
                .addGap(14, 14, 14))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ButtonRefreshAvailabilitySerie)
                    .addComponent(ButtonAddSerie)
                    .addComponent(SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonOptions))
                .addGap(14, 14, 14))
        );

        SearchBox.getAccessibleContext().setAccessibleName("SearchBox");
        SearchBox.getAccessibleContext().setAccessibleDescription("");

        jSplitPane1.setLeftComponent(Header);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(jPanel1);

        jSplitPane1.setRightComponent(jScrollPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRefreshAvailabilitySerieActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonRefreshAvailabilitySerieActionPerformed
        jPanel1.removeAll();

        for (var serie : managerSerie.getSeries()) {
            jPanel1.add(new SerieItem(serie));
        }

        jPanel1.revalidate();
        jPanel1.repaint();

    }// GEN-LAST:event_ButtonRefreshAvailabilitySerieActionPerformed

    private void ButtonAddSerieActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonAddSerieActionPerformed
        jPanel1.add(new SerieItem(managerSerie.addSerie()));

        jPanel1.revalidate();
        jPanel1.repaint();
    }// GEN-LAST:event_ButtonAddSerieActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddSerie;
    private javax.swing.JButton ButtonOptions;
    private javax.swing.JButton ButtonRefreshAvailabilitySerie;
    private javax.swing.JPanel Header;
    private javax.swing.JTextField SearchBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
