/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views.components;

import com.mycompany.models.SerieElement;

/**
 *
 * @author famar
 */
public class SerieItem extends javax.swing.JPanel {
    public final SerieElement serie;

    /**
     * Creates new form SerieItem
     */
    public SerieItem(SerieElement serie) {
        this.serie = serie;
        initComponents();
        
        //TODO: hacer que cuando cambies valores en los inputs se cambien en el objeto y que añada un boton para reemplazar cambios o descartarlos
        //FIXME: hacer que todos los elementos tengan el background del color de este componente, tengo que actualizar el bg de todos los elementos
        
        this.TitleField.setText(this.serie.title);
        this.LinkField.setText(this.serie.link);
        this.ChapterSpinner.setValue(this.serie.chapter);
        this.SeasonSpinner.setValue(this.serie.season);
        this.StateComboBox.setSelectedIndex(this.serie.state.value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        TitleField = new javax.swing.JTextField();
        LinkField = new javax.swing.JTextField();
        ChapterSpinner = new javax.swing.JSpinner();
        SeasonSpinner = new javax.swing.JSpinner();
        StateComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(getBackground());
        setFocusCycleRoot(true);
        setFocusTraversalPolicyProvider(true);
        setMaximumSize(new java.awt.Dimension(100000, 100000));
        setMinimumSize(new java.awt.Dimension(500, 100));
        setLayout(new java.awt.CardLayout());

        jSplitPane1.setBackground(getBackground());
        jSplitPane1.setDividerLocation(25);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setBackground(getBackground());

        TitleField.setMaximumSize(new java.awt.Dimension(300, 100));
        TitleField.setMinimumSize(new java.awt.Dimension(68, 100));
        jPanel2.add(TitleField);

        LinkField.setMaximumSize(new java.awt.Dimension(300, 100));
        jPanel2.add(LinkField);

        ChapterSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(ChapterSpinner);

        SeasonSpinner.setModel(new javax.swing.SpinnerNumberModel());
        jPanel2.add(SeasonSpinner);

        StateComboBox.setMaximumRowCount(3);
        StateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pending", "see", "finalized" }));
        jPanel2.add(StateComboBox);

        jSplitPane1.setBottomComponent(jPanel2);

        jPanel3.setBackground(getBackground());

        jLabel1.setText("Title");
        jPanel3.add(jLabel1);

        jLabel2.setText("Link");
        jPanel3.add(jLabel2);

        jLabel3.setText("Chapter");
        jPanel3.add(jLabel3);

        jLabel4.setText("Season");
        jPanel3.add(jLabel4);

        jLabel5.setText("State");
        jPanel3.add(jLabel5);

        jSplitPane1.setLeftComponent(jPanel3);

        add(jSplitPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ChapterSpinner;
    private javax.swing.JTextField LinkField;
    private javax.swing.JSpinner SeasonSpinner;
    private javax.swing.JComboBox<String> StateComboBox;
    private javax.swing.JTextField TitleField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

}
